apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "premyom-s3-explorer.fullname" . }}
  labels:
    {{- include "premyom-s3-explorer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: filebrowser
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: filebrowser
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: filebrowser
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.extraVault.addr | default "http://vault.vault.svc.cluster.local:8200" | quote }}
            - name: VAULT_K8S_ROLE
              value: {{ .Values.extraVault.k8sRole | default "premyom-s3-read" | quote }}
            - name: ONYXIA_USER_GROUPS
              value: {{ toJson (.Values.premyom.userGroupsJson | default (list)) | quote }}
            - name: PREMYOM_S3_MOUNT_ENABLED
              value: {{ (.Values.premyom.s3Mount.enabled | default "false") | quote }}
            - name: PREMYOM_S3_NONHDS_ENDPOINT_HOST
              value: {{ (.Values.premyom.s3Mount.nonHdsEndpointHost | default "") | quote }}
            - name: PREMYOM_S3_HDS_ENDPOINT_HOST
              value: {{ (.Values.premyom.s3Mount.hdsEndpointHost | default "") | quote }}
            - name: PREMYOM_S3_VAULT_NONHDS_PATH
              value: {{ (.Values.premyom.s3Mount.vaultNonHdsPath | default "") | quote }}
            - name: PREMYOM_S3_VAULT_HDS_PATH
              value: {{ (.Values.premyom.s3Mount.vaultHdsPath | default "") | quote }}
            - name: PREMYOM_S3_MOUNT_ROOT
              value: {{ (.Values.premyom.s3Mount.mountRoot | default "/mnt/s3") | quote }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: filebrowser-db
              mountPath: /var/lib/filebrowser
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: filebrowser-db
          emptyDir: {}
