{{- if and .Values.sso.ingress.enabled (eq (default "forwardAuth" .Values.sso.mode) "embedded") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "premyom-s3-explorer.fullname" . }}-oauth2-callback-ingress
  labels:
    {{- include "premyom-s3-explorer.labels" . | nindent 4 }}
  annotations:
{{- if .Values.sso.ingress.annotations }}
{{- $ann := deepCopy .Values.sso.ingress.annotations }}
{{- $_ := unset $ann "traefik.ingress.kubernetes.io/router.middlewares" }}
{{ toYaml $ann | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.sso.ingress.ingressClassName }}
  ingressClassName: {{ .Values.sso.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.sso.ingress.tls }}
  tls:
    - hosts:
        - {{ include "premyom-s3-explorer.centralHost" . | quote }}
  {{- end }}
  rules:
    - host: {{ include "premyom-s3-explorer.centralHost" . | quote }}
      http:
        paths:
          - path: {{ printf "/oauth2/%s" .Release.Name }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "premyom-s3-explorer.fullname" . }}-oauth2-proxy
                port:
                  number: 8080
{{- end }}
