{{- /*
Route dédiée au callback OIDC en mode `embedded`.

Voir `premyom-code-server`: on utilise un IngressRoute Traefik plutôt qu'un Ingress Kubernetes,
pour éviter qu'Onyxia ouvre l'endpoint de callback (proxy-prefix) au lieu du service.
*/ -}}
{{- if and .Values.sso.ingress.enabled (eq (default "forwardAuth" .Values.sso.mode) "embedded") -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "premyom-s3-explorer.fullname" . }}-oauth2-callback
  labels:
    {{- include "premyom-s3-explorer.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ ternary "websecure" "web" (default false .Values.sso.ingress.tls) }}
  routes:
    - match: {{ printf "Host(`%s`) && PathPrefix(`/premyom-oauth2/%s`)" (include "premyom-s3-explorer.centralHost" .) .Release.Name | quote }}
      kind: Rule
      services:
        - name: {{ include "premyom-s3-explorer.fullname" . }}-oauth2-proxy
          port: 8080
  {{- if .Values.sso.ingress.tls }}
  tls:
    certResolver: le
  {{- end }}
{{- end }}
