apiVersion: v1
kind: Service
metadata:
  name: {{ include "premyom-s3-explorer.fullname" . }}-filebrowser
  labels:
    {{- include "premyom-s3-explorer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: filebrowser
  ports:
    - name: http
      port: 8080
      targetPort: 8080

