{{- if .Values.sso.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "premyom-code-server.fullname" . }}-ingress
  labels:
    {{- include "premyom-code-server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.sso.ingress.annotations }}
    {{- toYaml .Values.sso.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- $mode := (default "forwardAuth" .Values.sso.mode) -}}
    {{- if not (hasKey (default dict .Values.sso.ingress.annotations) "traefik.ingress.kubernetes.io/router.middlewares") }}
    {{- if eq $mode "embedded" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-oauth2-redirect@kubernetescrd" .Release.Namespace (include "premyom-code-server.fullname" .) | quote }}
    {{- else if eq $mode "forwardAuth" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.sso.forwardAuth.middleware | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.sso.ingress.ingressClassName }}
  ingressClassName: {{ .Values.sso.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.sso.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.sso.ingress.hostname | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.sso.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.sso.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                {{- if eq (default "forwardAuth" .Values.sso.mode) "embedded" }}
                name: {{ include "premyom-code-server.fullname" . }}-oauth2-proxy
                {{- else }}
                name: {{ include "premyom-code-server.fullname" . }}-vscode-python
                {{- end }}
                port:
                  number: 8080
{{- end }}
