{{- if .Values.sso.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "premyom-code-server.fullname" . }}-sso
  labels:
    {{- include "premyom-code-server.labels" . | nindent 4 }}
  {{- with .Values.sso.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.sso.ingress.ingressClassName }}
  ingressClassName: {{ .Values.sso.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.sso.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.sso.ingress.hostname | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.sso.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.sso.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "premyom-code-server.fullname" . }}-oauth2-proxy
                port:
                  number: 8080
{{- end }}
