{{- if eq (default "forwardAuth" .Values.sso.mode) "embedded" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "premyom-code-server.fullname" . }}-oauth2-proxy
  labels:
    {{- include "premyom-code-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          imagePullPolicy: IfNotPresent
          args:
            - --provider=oidc
            - "--oidc-issuer-url={{ .Values.sso.issuerUrl }}"
            - --email-domain=*
            - --scope=openid profile email
            - --http-address=0.0.0.0:4180
            - "--proxy-prefix=/oauth2/{{ .Release.Name }}"
            - --reverse-proxy=true
            - --cookie-secure=true
            - '--cookie-name={{ include "premyom-code-server.cookieName" . }}'
            - '--cookie-domain={{ include "premyom-code-server.cookieDomain" . }}'
            - '--whitelist-domain={{ include "premyom-code-server.whitelistDomain" . }}'
            - --cookie-samesite=lax
            - --cookie-csrf-per-request=true
            - --skip-auth-preflight=true
            - "--redirect-url={{ include "premyom-code-server.redirectUrl" . }}"
            - --skip-provider-button=true
            - --set-authorization-header=true
            - --pass-access-token=true
            - --pass-user-headers=true
            - --cookie-refresh=1h
            - --cookie-expire=8h
            - --session-store-type=cookie
            - "--upstream=http://{{ include "premyom-code-server.fullname" . }}-vscode-python:8080/"
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.secretName }}
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.secretName }}
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.secretName }}
                  key: cookie-secret
          ports:
            - name: http
              containerPort: 4180
          readinessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 10
            periodSeconds: 10
{{- end }}
