replicaCount: 1

image:
  repository: stephanerenouard/onyxia-vscode
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

# Ingress géré par Onyxia (hébergé par Traefik)
ingress:
  enabled: true

  # Hostname sera injecté par Onyxia (ingress.hostname)
  hostname: ""

  # ingressClassName + annotations sont peuplés à partir de la région
  ingressClassName: ""
  annotations: {}
