apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-python-custom.fullname" . }}
  labels:
    app: {{ include "vscode-python-custom.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vscode-python-custom.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "vscode-python-custom.name" . }}
    spec:
      containers:
        - name: vscode-python-custom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: 8080
