apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode-python-custom.fullname" . }}
  labels:
    app: {{ include "vscode-python-custom.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "vscode-python-custom.name" . }}

